import Head from "next/head";
import { useState } from "react";
import Footer from "../../components/Footer";
import MoviesCards from "../../components/MoviesCards";
import Navbar from "../../components/Navbar";


const movies = (props) => {
    const {movies} = props
    console.log(movies.results);
    const [movieList , setMovieList]  = useState(movies?.results)
    return (
        <>
           <Head>
        <title>Movie: info</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <Navbar></Navbar>
 

      <main>
      <section className="container mx-auto py-10">
        <div className="title-area py-20 bg-gradient-to-r from-primary to-primary/50">
        <h2 className="text-4xl text-white font-bold text-center"> Popular Movies of 2022</h2>
        </div>
           
            <div className="grid grid-cols-4 gap-4 mx-auto">

            {
                movieList.map( item => <MoviesCards key={item.id}
                item={item}
                ></MoviesCards>
                )
            }
            </div>
        </section>
      </main>

     <Footer></Footer>
    </>
   
    );
};

export default movies;
export const getStaticProps = async (ctx) => {
    const res = await fetch(`https://api.themoviedb.org/3/discover/movie?sort_by=popularity.desc&api_key=${process.env.TMDB_APIKEY}`)
    const data =await res.json();
    return {
        props:{
            movies:data
        }
    }
}

